card_library/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('main_auth.urls')),
    path('', include('main.urls')),
    path('', include('profiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main.views.public_views import IndexView, ExpansionSetListView, ExpansionSetCardListView, CardDetailView
from main.views.user_views import add_card, user_collection, missing_cards_list, increase_collected_card_count, \
    remove_collected_card_copies, delete_collection_card

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('sets/', ExpansionSetListView.as_view(), name='set_list'),
    path('sets/<int:pk>/', ExpansionSetCardListView.as_view(), name='card_list'),
    path('cards/<int:pk>/', CardDetailView.as_view(), name='card_detail'),
    path('cards/add/<int:pk>/', add_card, name='add_card'),
    path('my-collection/', user_collection, name='user_collection'),
    path('my-collection/missing/', missing_cards_list, name='missing'),
    path('my-collection/add/<int:pk>/', increase_collected_card_count, name='add_copies'),
    path('my-collection/remove/<int:pk>/', remove_collected_card_copies, name='remove_copies'),
    path('my-collection/delete/<int:pk>/', delete_collection_card, name='delete_user_card'),
]

main/models.py
from django.db import models


# Create your models here.
class ExpansionSet(models.Model):
    name = models.CharField(max_length=50, blank=False)
    card_count = models.PositiveIntegerField(blank=False)
    image = models.ImageField(upload_to='card_set_images', blank=False)

    def __str__(self):
        return self.name


class Card(models.Model):
    hero_classes = [
        ('demon_hunter', 'Demon Hunter'),
        ('druid', 'Druid'),
        ('hunter', 'Hunter'),
        ('mage', 'Mage'),
        ('paladin', 'Paladin'),
        ('priest', 'Priest'),
        ('rogue', 'Rogue'),
        ('shaman', 'Shaman'),
        ('warlock', 'Warlock'),
        ('warrior', 'Warrior'),
        ('neutral', 'Neutral'),
    ]

    rarities = [
        ('free', 'Free'),
        ('common', 'Common'),
        ('rare', 'Rare'),
        ('epic', 'Epic'),
        ('legendary', 'Legendary'),
    ]

    card_types = [
        ('minion', 'Minion'),
        ('spell', 'Spell'),
        ('weapon', 'Weapon'),
        ('hero_card', 'Hero Card'),
    ]

    name = models.CharField(max_length=30, blank=False)
    card_type = models.CharField(max_length=9, blank=False, choices=card_types)
    hero_class = models.CharField(max_length=12, blank=False, choices=hero_classes)
    mana_cost = models.PositiveIntegerField(blank=False)
    rarity = models.CharField(max_length=9, blank=False, choices=rarities)
    image = models.ImageField(upload_to='card_images', blank=False)
    expansion_set = models.ForeignKey(ExpansionSet, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

main/models/card.py
from django.db import models
from main.models.expansion_set import ExpansionSet


class Card(models.Model):
    hero_classes = [
        ('demon_hunter', 'Demon Hunter'),
        ('druid', 'Druid'),
        ('hunter', 'Hunter'),
        ('mage', 'Mage'),
        ('paladin', 'Paladin'),
        ('priest', 'Priest'),
        ('rogue', 'Rogue'),
        ('shaman', 'Shaman'),
        ('warlock', 'Warlock'),
        ('warrior', 'Warrior'),
    ]

    rarities = [
        ('free', 'Free'),
        ('common', 'Common'),
        ('rare', 'Rare'),
        ('epic', 'Epic'),
        ('legendary', 'Legendary'),
    ]

    card_types = [
        ('minion', 'Minion'),
        ('spell', 'Spell'),
        ('weapon', 'Weapon'),
        ('hero_card', 'Hero Card'),
    ]

    name = models.CharField(max_length=30, blank=False)
    card_type = models.CharField(max_length=9, blank=False, choices=card_types)
    hero_class = models.CharField(max_length=12, blank=True, choices=hero_classes)
    mana_cost = models.PositiveIntegerField(blank=False)
    rarity = models.CharField(max_length=9, blank=False, choices=rarities)
    image = models.ImageField(upload_to='card_images', blank=False)
    expansion_set = models.ForeignKey(ExpansionSet, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

main/models/class_portrait.py
from django.db import models


class ClassPortrait(models.Model):
    hero_classes = [
        ('demon_hunter', 'Demon Hunter'),
        ('druid', 'Druid'),
        ('hunter', 'Hunter'),
        ('mage', 'Mage'),
        ('paladin', 'Paladin'),
        ('priest', 'Priest'),
        ('rogue', 'Rogue'),
        ('shaman', 'Shaman'),
        ('warlock', 'Warlock'),
        ('warrior', 'Warrior')
    ]

    name = models.CharField(max_length=20, blank=False)
    image = models.ImageField(upload_to='class_portrait_images', blank=False)
    hero_class = models.CharField(max_length=12, blank=True, choices=hero_classes)

    def __str__(self):
        return self.name

main/models/collection_card.py
from django.contrib.auth.models import User
from django.db import models
from main.models.card import Card


class CollectionCard(models.Model):
    card = models.ForeignKey(Card, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    copies = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.card.name

main/models/expansion_set.py
from django.db import models


class ExpansionSet(models.Model):
    name = models.CharField(max_length=50, blank=False)
    card_count = models.PositiveIntegerField(blank=False)
    image = models.ImageField(upload_to='card_set_images', blank=False)
    release_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.name

main/forms.py
from django import forms
from main.models.expansion_set import ExpansionSet


class ChangeCardCountForm(forms.Form):
    count = forms.IntegerField(initial=1, min_value=1, label='Copies')


class SelectExpSetForm(forms.Form):
    expansion_set = forms.ModelChoiceField(ExpansionSet.objects.all(), required=False, label='Select Expansion Set')

main/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from main.models.expansion_set import ExpansionSet
from main.models.card import Card
from main.models.collection_card import CollectionCard

from main.forms import ChangeCardCountForm, SelectExpSetForm

from main_core.decorators import group_required
from main_core.reusables import get_next_url, get_exp_set_id, get_card_list, is_collection_complete


def index(request):
    sets = ExpansionSet.objects.order_by('-release_date')[:3]

    return render(request, 'main/index.html', context={'sets': sets})


class ExpansionSetListView(ListView):
    template_name = 'main/set_list.html'
    model = ExpansionSet
    context_object_name = 'sets'
    ordering = ['-release_date']
    paginate_by = 2


class ExpansionSetCardListView(ListView):
    template_name = 'main/card_list.html'
    model = Card
    context_object_name = 'cards'
    paginate_by = 8

    def get_queryset(self):
        exp_set = get_object_or_404(ExpansionSet, pk=self.kwargs.get('pk'))
        cards = exp_set.card_set.order_by('hero_class', 'name')

        return cards


class CardDetailView(DetailView):
    model = Card


@group_required(groups=['Regular User'])
def add_card(request, pk):
    card = Card.objects.get(pk=pk)

    if request.method == 'GET':
        form = ChangeCardCountForm()

        context = {
            'form': form,
            'card': card,
        }

        return render(request, 'main/add_card.html', context)
    else:
        form = ChangeCardCountForm(request.POST)

        if form.is_valid():
            user = request.user
            copies_to_add = form.cleaned_data['count']
            result = user.collectioncard_set.filter(card__name=card.name)

            if result:
                collected_card = result[0]
                collected_card.copies += copies_to_add
                collected_card.save()
            else:
                new_card = CollectionCard(card=card, user=user, copies=copies_to_add)
                new_card.save()

            return redirect(get_next_url(request.POST))

        context = {
            'form': form,
            'card': card,
        }

        return render(request, 'main/add_card.html', context)


@group_required(groups=['Regular User'])
def increase_collected_card_count(request, pk):
    card = request.user.collectioncard_set.get(pk=pk)

    if request.method == 'GET':
        form = ChangeCardCountForm()

        context = {
            'form': form,
            'card': card,
        }

        return render(request, 'main/add_copies.html', context)
    else:
        form = ChangeCardCountForm(request.POST)

        if form.is_valid():
            copies_to_add = form.cleaned_data['count']

            card.copies += copies_to_add
            card.save()

            return redirect(get_next_url(request.POST))

        context = {
            'form': form,
            'card': card,
        }

        return render(request, 'main/add_copies.html', context)


@group_required(groups=['Regular User'])
def remove_collected_card_copies(request, pk):
    card = request.user.collectioncard_set.get(pk=pk)

    if request.method == 'GET':
        form = ChangeCardCountForm()

        context = {
            'form': form,
            'card': card,
        }

        return render(request, 'main/remove_copies.html', context)
    else:
        form = ChangeCardCountForm(request.POST)

        if form.is_valid():
            if card.copies < form.cleaned_data['count']:
                form.add_error('count', 'You can not delete more copies than you already own.')

                context = {
                    'form': form,
                    'card': card,
                }

                return render(request, 'main/remove_copies.html', context)

            copies_to_remove = form.cleaned_data['count']
            card.copies -= copies_to_remove

            if card.copies == 0:
                card.delete()
            else:
                card.save()

            return redirect(get_next_url(request.POST))

        context = {
            'form': form,
            'card': card,
        }

        return render(request, 'main/remove_copies.html', context)


@group_required(groups=['Regular User'])
def delete_collection_card(request, pk):
    card = request.user.collectioncard_set.get(pk=pk)

    if request.method == 'GET':
        context = {
            'card': card,
        }

        return render(request, 'main/delete_user_card.html', context)
    else:
        card.delete()
        return redirect(get_next_url(request.POST))


@group_required(groups=['Regular User'])
def user_collection(request):
    user = request.user
    result = get_exp_set_id(request.GET)

    if not result:
        cards = user.collectioncard_set.order_by('card__expansion_set__name', 'card__hero_class', 'card__name')

        paginator = Paginator(cards, 8)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
            'form': SelectExpSetForm(),
            'exp_set': '',
            'cards': cards,
            'complete': is_collection_complete(user),
            'total_card_count': Card.objects.all().count(),
            'is_paginated': True,
            'page_obj': page_obj,
        }

        return render(request, 'main/user_collection.html', context)
    else:
        exp_set = ExpansionSet.objects.get(pk=result)
        cards = user.collectioncard_set.filter(card__expansion_set=exp_set).order_by('card__hero_class', 'card__name')

        paginator = Paginator(cards, 8)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
            'form': SelectExpSetForm(initial={'expansion_set': result}),
            'exp_set': exp_set,
            'cards': cards,
            'complete': is_collection_complete(user, expansion=exp_set),
            'exp_set_card_count': Card.objects.filter(expansion_set=exp_set).count(),
            'is_paginated': True,
            'page_obj': page_obj,
        }

        return render(request, 'main/user_collection.html', context)


@group_required(groups=['Regular User'])
def missing_cards_list(request):
    user = request.user
    result = get_exp_set_id(request.GET)

    if not result:
        missing_cards = get_card_list(user)

        paginator = Paginator(missing_cards, 8)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
            'form': SelectExpSetForm(),
            'exp_set': '',
            'cards': missing_cards,
            'is_paginated': True,
            'page_obj': page_obj,
        }

        return render(request, 'main/missing_cards.html', context)
    else:
        exp_set = ExpansionSet.objects.get(pk=result)
        missing_cards = get_card_list(user, expansion=exp_set)

        paginator = Paginator(missing_cards, 8)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
            'form': SelectExpSetForm(initial={'expansion_set': result}),
            'exp_set': exp_set,
            'cards': missing_cards,
            'is_paginated': True,
            'page_obj': page_obj,
        }

        return render(request, 'main/missing_cards.html', context)

main/views/public_views.py
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView, TemplateView

from main.models.card import Card
from main.models.expansion_set import ExpansionSet


class IndexView(TemplateView):
    """Renders the landing page with the 3 most recently released expansion sets."""

    template_name = 'main/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sets'] = ExpansionSet.objects.order_by('-release_date')[:3]

        return context


class ExpansionSetListView(ListView):
    """Renders a list view with all expansion sets in the database, 2 per page, starting with the most recent one."""

    template_name = 'main/set_list.html'
    model = ExpansionSet
    context_object_name = 'sets'
    ordering = ['-release_date']
    paginate_by = 2


class ExpansionSetCardListView(ListView):
    """Renders a list view with all cards in an expansion set with 8 cards per page.

    Cards are ordered by hero class and then by name.
    """

    template_name = 'main/card_list.html'
    model = Card
    context_object_name = 'cards'
    paginate_by = 8

    def get_queryset(self):
        exp_set = get_object_or_404(ExpansionSet, pk=self.kwargs.get('pk'))
        cards = exp_set.card_set.order_by('-hero_class', 'mana_cost')

        return cards

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['set'] = get_object_or_404(ExpansionSet, pk=self.kwargs.get('pk'))

        return context


class CardDetailView(DetailView):
    """Renders a detailed look of a specific card."""

    model = Card

templates/main/add_card.html
{% extends 'common/base.html' %}

{% block title %}Add card{% endblock %}

{% block content %}
    <div class="container">
        <div class="items-container">
            <div class="item">
                <img src="{{ card.image.url }}" alt="Image of {{ card.name }}.">
                <form method="POST" action="{% url 'add_card' card.id %}">
                    {% csrf_token %}
                    {{ form }}
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                    <div class="text-center">
                        <button class="btn btn-dark btn-sm mt-3">Add card</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/main/add_copies.html
{% extends 'common/base.html' %}

{% block title %}Add copies{% endblock %}

{% block content %}
    <div class="container">
        <div class="items-container">
            <div class="item">
                <img src="{{ card.card.image.url }}" alt="Image of {{ card.card.name }}.">
                <p class="text-center font-weight-bold">Copies owned: {{ card.copies }}</p>
                <form method="POST" action="{% url 'add_copies' card.id %}">
                    {% csrf_token %}
                    {{ form }}
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                    <div class="text-center">
                        <button class="btn btn-dark btn-sm mt-3">Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/main/card_detail.html
{% extends 'common/base.html' %}

{% block title %}Card details{% endblock %}

{% block content %}
    <div class="d-flex justify-content-center align-items-center">
        <div class="card m-3" style="width: 18rem;">
            <img class="card-img-top" src="{{ card.image.url }}" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">{{ card.name }}</h5>
                <p class="card-text text-center">Type: {{ card.card_type|title }}</p>
                {% if card.hero_class %}
                    <p class="card-text">Class: {{ card.get_hero_class_display }}</p>
                {% else %}
                    <p class="card-text">Class: Neutral</p>
                {% endif %}
                <p class="card-text">Mana cost: {{ card.mana_cost }}</p>
                <p class="card-text">Rarity: {{ card.rarity|title }}</p>
            </div>
        </div>
    </div>
    <div class="text-center">
        <a class="btn btn-dark btn-sm mt-2" href="javascript:history.back()">Go back</a>
    </div>
{% endblock %}

templates/main/card_info.html
{% extends 'common/base.html' %}

{% block title %}Card details{% endblock %}

{% block content %}
    <div class="d-flex justify-content-center align-items-center">
        <div class="card m-3" style="width: 18rem;">
            <img class="card-img-top" src="{{ card.image.url }}" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">{{ card.name }}</h5>
                <p class="card-text text-center">Type: {{ card.card_type|title }}</p>
                <p class="card-text">Class: {{ card.hero_class|title }}</p>
                <p class="card-text">Mana cost: {{ card.mana_cost }}</p>
                <p class="card-text">Rarity: {{ card.rarity|title }}</p>
            </div>
        </div>
    </div>
    <div class="text-center">
        <a class="btn btn-primary btn-sm mt-2" href="javascript:history.back()">Go back</a>
    </div>
{% endblock %}

templates/main/card_list.html
{% extends 'common/base.html' %}

{% block title %}Card list{% endblock %}

{% block content %}
    <h1>{{ set.name }}</h1>
    {% include 'partials/card_loop_detailed.html' %}
    <div class="d-flex">
        <div class="mx-auto">
            {% include 'common/pagination.html' %}
        </div>
    </div>
    <div class="text-center">
        <a class="btn btn-dark btn-sm mt-2" href="{% url 'set_list' %}">Back to sets</a>
    </div>
{% endblock %}

templates/main/delete_user_card.html
{% extends 'common/base.html' %}

{% block title %}Delete Card{% endblock %}

{% block content %}
    <h1>Remove card and all copies from your collection?</h1>
    <div class="container">
        <div class="items-container">
            <div class="item">
                <img src="{{ card.card.image.url }}" alt="Image of {{ card.card.name }}">
                <p class="text-center">Copies owned: {{ card.copies }}</p>
                <form action="{% url 'delete_user_card' card.id %}" method="post">
                    <div class="text-center">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ request.GET.next }}">
                        <button class="btn btn-danger btn-sm">Yes, delete</button>
                    </div>
                </form>
                <div class="text-center">
                    <a class="btn btn-dark btn-sm mt-2" href="javascript:history.back()">No, go back</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/main/index.html
{% extends 'common/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>Hearthstone Collection Tracker</h1>
    <div class="float-left mt-5 ml-4">
        <h2>Latest sets:</h2>
    </div>
    <div class="float-left mx-3">
        <div class="row">
            {% for set in sets %}
                <div class="col-md-4 col-sm-4">
                    <div class="card m-3">
                        <img class="card-img-top" src="{{ set.image.url }}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">{{ set.name }}</h5>
                            <p class="card-text">Cards: {{ set.card_count }}</p>
                            {% if set.release_date %}
                                <p class="card-text">Release date: {{ set.release_date }}</p>
                            {% endif %}
                            <a href="{% url 'card_list' set.id %}" class="btn btn-dark btn-sm">View cards</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/main/missing_cards.html
{% extends 'common/base.html' %}

{% block title %}Missing cards{% endblock %}

{% block content %}
    <div class="container">
        <div class="items-container">
            <div class="item">
                <form method="get" action="{% url 'missing' %}">
                    {{ form }}
                    <div class="text-center">
                        <button class="btn btn-dark btn-sm mt-3">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% if not cards %}
        {% if exp_set %}
            <h1>You have collected every card from {{ exp_set.name }}!</h1>
        {% else %}
            <h1>Congratulations, your collection is complete!</h1>
        {% endif %}
    {% else %}
        {% if exp_set %}
            <h1>Missing cards from {{ exp_set.name }}:</h1>
        {% else %}
            <h1>All missing cards:</h1>
        {% endif %}
    {% endif %}
    <div class="container">
    <div class="row">
        {% for card in cards %}
            <div class="col-md-3">
                <div class="card m-3">
                    <img class="card-img-top" src="{{ card.image.url }}" alt="Card image cap">
                    <div class="card-body">
                        <div class="text-center">
                            <a href="{% url 'card_detail' card.id %}" class="btn btn-dark btn-sm">Card details</a>
                            {% if user.is_authenticated %}
                                <a href="{% url 'add_card' card.id %}?next={{ request.path|urlencode }}"
                                   class="btn btn-dark btn-sm">Add card</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/main/remove_copies.html
{% extends 'common/base.html' %}

{% block title %}Remove copies{% endblock %}

{% block content %}
    <div class="container">
        <div class="items-container">
            <div class="item">
                <img src="{{ card.card.image.url }}" alt="Image of {{ card.name }}.">
                <p class="text-center font-weight-bold">Copies owned: {{ card.copies }}</p>
            </div>
        </div>
        <div class="items-container">
            <div class="item">
                <form method="POST" action="{% url 'remove_copies' card.id %}">
                    {% csrf_token %}
                    {{ form }}
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                    <div class="text-center">
                        <button class="btn btn-dark btn-sm mt-3">Remove</button>
                        <a href="{% url 'user_collection' %}" class="btn btn-dark btn-sm mt-3">Go back</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/main/set_list.html
{% extends 'common/base.html' %}

{% block title %}All sets{% endblock %}

{% block content %}
    {% include 'partials/exp_set_loop.html' %}
    <div class="d-flex">
        <div class="mx-auto">
            {% include 'common/pagination.html' %}
        </div>
    </div>
{% endblock %}

templates/main/user_collection.html
{% extends 'common/base.html' %}

{% block title %}My collection{% endblock %}

{% block content %}
    {% include 'partials/exp_set_select.html' %}
    {% if not exp_set %}
        {% if complete %}
            <h1>Congratulations, you have a play set of all {{ total_card_count }} cards!</h1>
        {% else %}
            <h1>{{ cards.count }}/{{ total_card_count }} unique cards collected:</h1>
        {% endif %}
    {% else %}
        {% if complete %}
            <h1>You have collected a play set of all {{ exp_set_card_count }} cards from {{ exp_set.name }}!</h1>
        {% else %}
            <h1>{{ cards.count }}/{{ exp_set_card_count }} unique cards collected from {{ exp_set.name }}:</h1>
        {% endif %}
    {% endif %}
    {% include 'partials/card_loop_basic.html' %}
{% endblock %}