card_library/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('main_auth.urls')),
    path('', include('main.urls')),
    path('', include('profiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main.views.public_views import IndexView, ExpansionSetListView, ExpansionSetCardListView, CardDetailView
from main.views.user_views import add_card, user_collection, missing_cards_list, increase_collected_card_count, \
    remove_collected_card_copies, delete_collection_card

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('sets/', ExpansionSetListView.as_view(), name='set_list'),
    path('sets/<int:pk>/', ExpansionSetCardListView.as_view(), name='card_list'),
    path('cards/<int:pk>/', CardDetailView.as_view(), name='card_detail'),
    path('cards/add/<int:pk>/', add_card, name='add_card'),
    path('my-collection/', user_collection, name='user_collection'),
    path('my-collection/missing/', missing_cards_list, name='missing'),
    path('my-collection/add/<int:pk>/', increase_collected_card_count, name='add_copies'),
    path('my-collection/remove/<int:pk>/', remove_collected_card_copies, name='remove_copies'),
    path('my-collection/delete/<int:pk>/', delete_collection_card, name='delete_user_card'),
]

profiles/urls.py
from django.urls import path

from profiles.views import user_profile, change_profile_picture

urlpatterns = [
    path('profile/', user_profile, name='user_profile'),
    path('profile/change-picture/', change_profile_picture, name='change_picture'),
    path('profile/change-picture/<int:pk>/', change_profile_picture, name='change_picture'),
]

main_auth/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from main.models.class_portrait import ClassPortrait
from main.models.expansion_set import ExpansionSet


class UserProfile(models.Model):
    hero_classes = [
        ('demon_hunter', 'Demon Hunter'),
        ('druid', 'Druid'),
        ('hunter', 'Hunter'),
        ('mage', 'Mage'),
        ('paladin', 'Paladin'),
        ('priest', 'Priest'),
        ('rogue', 'Rogue'),
        ('shaman', 'Shaman'),
        ('warlock', 'Warlock'),
        ('warrior', 'Warrior'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ForeignKey(ClassPortrait, blank=True, null=True, on_delete=models.DO_NOTHING)
    favourite_class = models.CharField(max_length=12, choices=hero_classes, blank=True)

    def __str__(self):
        return self.user.username

profiles/models.py
from django.db import models

# Create your models here.

profiles/forms.py
from django import forms

from main_auth.models import UserProfile


class FavouriteClassForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('favourite_class',)

profiles/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from main.models.card import Card
from main.models.class_portrait import ClassPortrait
from profiles.forms import FavouriteClassForm


@login_required
def user_profile(request):
    user = request.user
    unique_user_sets = user.collectioncard_set.distinct('card__expansion_set')

    if request.method == 'GET':
        context = {
            'profile_user': user,
            'profile': user.userprofile,
            'form': FavouriteClassForm(),
            'favourite_class': user.userprofile.favourite_class,
            'user_sets': unique_user_sets,
            'total_user_cards': user.collectioncard_set.count(),
            'total_cards': Card.objects.count(),
        }

        return render(request, 'profiles/user_profile.html', context)
    else:
        form = FavouriteClassForm(request.POST, instance=user.userprofile)

        if form.is_valid():
            form.save()
            return redirect('user_profile')

        return redirect('user_profile')


@login_required
def change_profile_picture(request, pk=None):
    if request.method == 'GET':
        classes = ClassPortrait.objects.order_by('hero_class')

        return render(request, 'profiles/change_picture.html', context={'classes': classes})
    else:
        user = request.user
        class_picture = ClassPortrait.objects.get(pk=pk)

        user.userprofile.profile_picture = class_picture
        user.userprofile.save()

        return redirect('user_profile')

templates/profiles/change_picture.html
{% extends 'common/base.html' %}

{% block title %}Change Picture{% endblock %}

{% block content %}
    <h2>Choose profile picture:</h2>
    <div class="container">
        <div class="row">
            {% for class in classes %}
                <div class="col-md-3">
                    <img class="rounded-circle mt-3" src="{{ class.image.url }}" alt="Hero Class Image"
                         width="200"
                         height="200">
                    <form action="{% url 'change_picture' class.id %}" method="post">
                        {% csrf_token %}
                        <div class="text-center">
                            <button class="btn btn-dark btn-sm mr-5 mt-3">Select</button>
                        </div>
                    </form>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/profiles/user_profile.html
{% extends 'common/base.html' %}
{% load user_collected_cards %}

{% block title %}Profile{% endblock %}

{% block content %}
    <div class="text-center">
        <h1>Greetings, {{ profile_user.username }}!</h1>
        <img class="rounded-circle mb-3" src="{{ profile.profile_picture.image.url }}" alt="Hero Class Image"
             width="200"
             height="200">
    </div>
    <form action="{% url 'change_picture' %}" method="get">
        <div class="text-center">
            <button class="btn btn-dark btn-sm">Change picture</button>
        </div>
    </form>
    <div class="text-center">
        {% if favourite_class %}
            <h2>Favourite class: {{ profile.get_favourite_class_display }}</h2>
            <div class="text-center mt-3">Change favourite class:</div>
        {% else %}
            <div class="text-center font-weight-bold mt-3">Set favourite class:</div>
        {% endif %}
    </div>
    <div class="container">
        <div class="items-container">
            <div class="item">
                <form method="POST" action="{% url 'user_profile' %}">
                    {% csrf_token %}
                    {{ form.favourite_class }}
                    <div class="text-center">
                        <button class="btn btn-dark btn-sm mt-3">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <h2>Total unique cards collected: {{ total_user_cards }}/{{ total_cards }}</h2>
    {% if user_sets %}
        <h2>My sets:</h2>
        <div class="container">
            <div class="row mt-5">
                {% for card in user_sets %}
                    <div class="col-md-4 col-sm-4">
                        <div class="card m-3">
                            <img class="card-img-top" src="{{ card.card.expansion_set.image.url }}"
                                 alt="Card image cap">
                            <div class="card-body">
                                <h5 class="card-title">{{ card.card.expansion_set.name }}</h5>
                                <p class="card-text">{% user_collected_cards profile_user card %}</p>
                                <div>
                                    <form action="{% url 'user_collection' %}" method="get">
                                        <input type="hidden" name="expansion_set"
                                               value="{{ card.card.expansion_set.id }}">
                                        <button class="btn btn-dark btn-sm">View my cards</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
{% endblock %}